### ISSUE TITLE
Mitgliederlevel bestehende Mitglieder bei Launch

### ISSUE THREAD

**Issue by timemb** [timemb/herzenspeople#1]
Frage:
Was ist mit den bereits angelegten Profilen von Mitgliedern, wenn wir starten? Die wissen ja noch nicht, dass der Bereich kostenpflichtig ist. Müssen die nochmal alles neu eingeben?

**Comment by timemb** [comment]
Wir werden die angelegten Mitglieder in das Kostenlose Mitgliederlevel ändern und können sie anschließend dann per E-Mail informieren, dass sie Ihr Mitgliedslevel selbst ändern können.

**Comment by KlaudiaSt** [comment]
Was ist dann mit dem angelegten Profil? Bleibt das bestehen oder wird es gelöscht?

**Comment by timemb** [comment]
Das Profil bleibt bestehen.
