### ISSUE TITLE
UST ID - Impressum

### ISSUE THREAD

**Issue by timemb** [timemb/herzenspeople#10]
Klaudia:
Ust-ID raus

**Comment by timemb** [comment]
Kommt auf die Unternehmensform an, aber ich meine UST-ID ist immer Pflicht. Bitte schau hier nochmal nach: https://www.e-recht24.de/impressum-generator.html

**Comment by timemb** [comment]
Klaudia:
Du bekommst meine Ust-ID, wenn ich sie habe

**Comment by KlaudiaSt** [comment]
Meine USt-ID lautet
DE 313 723 701

**Comment by timemb** [comment]
ist im Impressum eingebaut
