### ISSUE TITLE
Verifizierung

### ISSUE THREAD

**Issue by timemb** [timemb/herzenspeople#14]
![nachrichten verifizierung](https://user-images.githubusercontent.com/13312142/30394915-84d0e68c-9892-11e7-81f2-4d760ed2ef28.png)

Klaudia:
Warum bekomme ich diese Nachricht? Bestätigung von Admin unnötig?!
Die Verifizierung sollten wir vereinfachen, in dem wir nur auf den Button drücken und somit bestätigen, dass derjenige mir persönlich bekannt ist und keine Nachricht darüber verschickt wird.

**Comment by timemb** [comment]
Ist derzeit so eingestellt, wie besprochen, dass ein Administrator die Verifizierung von Mitgliedern freigeben muss. Können wir gerne ändern.

**Comment by timemb** [comment]
Klaudia:
Ich denke, dass die Freigabe über einen Admin irgendwann zuviel wird. Oder was meinst du?

**Comment by timemb** [comment]
Die Verifizierung kann gerne komplett an die Community abgegeben werden. Fördert auch den Austausch untereinander. Die Anzahl der Verifikationen die ein Mitgliedslevel braucht können wir einstellen und dann wird ein Mitglied automatisch verifiziert.

Hier die Einstellungsmöglichkeiten, die wir pro Mitgliederlevel einstellen können:
![einstellunge member verification](https://user-images.githubusercontent.com/13312142/30395095-1564da5a-9893-11e7-9d37-8128ba726c7a.png)

**Comment by KlaudiaSt** [comment]
Was spricht dagegen, dass jeder jeden verifizieren kann? Das heisst doch nur, dass man sich persönlich kennt, oder?

**Comment by timemb** [comment]
Ja das sollte die Idee dahinter sein, das an die Community "abzugeben". Ich finde es gut, wenn jeder jeden verifizieren kann.

Ich stelle das dann also so ein, dass die Community selbst regelt ohne das ein Admin das abnicken muss?

**Comment by KlaudiaSt** [comment]
Ja
