### ISSUE TITLE
Probleme mit Portalen

### ISSUE THREAD

**Issue by KlaudiaSt** [timemb/herzenspeople#25]
Es gibt Probleme mit Portalen die über verschlüsselte Verbindung aufgerufen werden, die erste Liste an Adressen aus Portalen ist voraussichtlich Mittwoch 13.09. einsehbar. 

Sind die Probleme lösbar?

**Comment by timemb** [comment]
Das versuchen wir zu klären. Du hast hierzu eine E-Mail von mir. (18.09.2017)

**Comment by KlaudiaSt** [comment]
Wie stellen sich die gecrawlten E-Mail-Adressen zusammen?

**Comment by KlaudiaSt** [comment]
Gibt es eine Möglichkeit, an die Adressen der gesicherten Datenbanken/Seiten zu kommen?

**Comment by timemb** [comment]
Thomas hat dieses Programm gefunden: http://t3n.de/news/e-mail-hunter-findest-alle-621496/

Das kann ausprobiert werden, wenn das jetzige Programm keine Lösung bietet.
