### ISSUE TITLE
Freundschaften bestätigen

### ISSUE THREAD

**Issue by KlaudiaSt** [timemb/herzenspeople#30]
Klaudia:
Bei FB ist das über ein Abo möglich.  Der Abonnierte sollte dann auch die Möglichkeit haben, seine Interessenten direkt über eine Mail bei Besonderheiten anzuschreiben. 
Tim: 
Das was du hier beschreibst sind Facebook-Seiten und bei uns im Bereich Seiten möglich. Updates der Seiten (egal ob eine Seite zu einem Unternehmen oder einer Person) können in den Aktivitäten auf der Pinnwand auftauchen. Seitenbetreiber können E-Mails/Nachrichten an alle Follower schicken. Ich würde dann jetzt Feundschaften wieder auf das Facebookbeispiel umstellen. Okay? 

Klaudia: Jaaa

**Comment by timemb** [comment]
umgestellt
