### ISSUE TITLE
Support-Seite programmieren

### ISSUE THREAD

**Issue by KlaudiaSt** [timemb/herzenspeople#31]
Klaudia:
Support-Seite programmieren     Dieser Aufwand verringert sich doch durch das neue PlugIn?
Tim:
Support ja, hier können wir ein E-Mailformular erstellen, ähnlich dem auf der Seite „Mitgestalten“. Es wird dann eine E-Mail mit den vorgegebenen Angaben an eine von uns definierte E-Mailadresse geschickt. 

Klaudia: Okay, machen

**Comment by timemb** [comment]
Seite Support erstellt.
https://www.herzensmenschen.com/se/support

Verlinkung befindet sich in der Fußzeile

**Comment by KlaudiaSt** [comment]
Gibt es etwas ähnliches in Deutsch wie GitHub?

Dann könnten wir doch den Support darüber machen?!
