### ISSUE TITLE
FAQ programmieren

### ISSUE THREAD

**Issue by KlaudiaSt** [timemb/herzenspeople#32]
Klaudia:
FAQ einfügen  mit dem neuen PlugIn?  
Tim:
Mit einem der neuen Plugins können wir ohne Programmierkenntnisse einfache Textseiten erstellen. Ich zeige dir gerne wo. Hier können wir für den Anfang Fragen und Antworten auf die wichtigsten Fragen unterbringen.

Klaudia:Okay, so machen wir das

**Comment by timemb** [comment]
Die nachstehenden Bilder können zur Vergrößerung angeklickt werden.

Vorgehen zum Bearbeiten der FAQ:
Wenn du eingeloggt bist und dem Link in den Adminbereich folgst, kannst du aus der Liste der Plugins das letzte Plugin aus der Liste auswählen "Static Pages, HTML Blocks and Multiple Forms Plugin"

![faq1](https://user-images.githubusercontent.com/13312142/31550156-b2f0309e-b030-11e7-88f6-75721752e50d.png)

Dann wechselst du innerhalb des Plugins auf den zweiten Reiter "Static Pages & HTML Blocks". Wie im Screenshot klickst du in der Tabelle dann bei dem Eintrag für 7 FAQ auf den Link zum Bearbeiten "edit".

![faq2](https://user-images.githubusercontent.com/13312142/31550239-f7413694-b030-11e7-9238-7c30ace31557.png)


Es öffnet sich der Bearbeitenmodus der Seite FAQ. Hier kann, wie im nachstehenden Bild zu sehen, der markierte Text durch die am häufigsten gestellten Fragen ersetzt werden.

![faq3](https://user-images.githubusercontent.com/13312142/31550431-9e0ce7a2-b031-11e7-9ad8-cdec583db0d7.png)
