### ISSUE TITLE
Land vor Bundesland

### ISSUE THREAD

**Issue by KlaudiaSt** [timemb/herzenspeople#33]
Land vor Bundesland 
Wenn ich das mache, ist das Bundesland auf einmal am Ende des Formulars         Support

**Comment by timemb** [comment]
Diese Felder werden in den Mitgliedprofilen nicht abgefragt. Sie liefern daher keine Ergebnisse.
Für die Suche mit Ortsbezug ist das Feld "Wo" zu benutzen.
