### ISSUE TITLE
Suche: Bundesland/Land

### ISSUE THREAD

**Issue by KlaudiaSt** [timemb/herzenspeople#34]
Was derzeit, egal was man macht, nur maximal 1 Ergebnis liefert ist die Suche über das Suchfeld Bundesland oder Land.

**Comment by timemb** [comment]
Wie in Issue #35 beschrieben. Wir Fragen Land und Bundesland bei den Mitgliedern nicht ab. Deswegen gibt es hier auch kein Ergebnis.
