### ISSUE TITLE
Plugin Paymentgateway

### ISSUE THREAD

**Issue by timemb** [timemb/herzenspeople#4]
für HeidelPay von YouNetCo
http://socialengine.younetco.com/advanced-payment-gateway.html

Problem: Jahresabo (Hier steht der Entwickler im direkten Austausch mit HeidelPay, um zu klären,   ob ein jährliches Abo technisch möglich ist.

**Comment by timemb** [comment]
Rückmeldung erhalten?
Mein Support Ticket wurde nun ohne Antwort gelöscht. Ich habe dieses noch nicht gekauft, bevor wir keine Antwort haben. Ich frage dies erneut an, aber ich denke eine wiederkehrende, automatische jährliche Bezahlung ist mit Heidelpay nicht zu machen. Ändert das was an der Entscheidung zum Anbieter und dem Plugin? Dieses zu aktivieren ist der letzte Schritt, da Test der Mitgliederlevel nicht mehr möglich ist, da man ja dann bezahlen muss.

**Comment by timemb** [comment]
Klaudia:
Im Moment haben wir keine kostengünstigere Alternative. Für die jährliche Zahlung haben wir ja 1 Jahr Zeit, bis sie sich wiederholt. Entweder wir haben dann was Anderes oder lassen die Inder programmieren.

**Comment by timemb** [comment]
Ich weiß nicht wie einfach/schwierig die Umstellung eines Zahlungsdienstanbieters ist. Stelle ich mir aufwändig vor. Wie es aussieht ist eine wiederkehrende, jährliche Zahlung von Seiten Heidelpay nicht möglich. Das kann man auch nicht von außen mit einer anderen Programmierung ändern, wenn das so ist. Dafür fehlt mir aber noch die Aussage, da mein Ticket ja gelöscht wurde. Eine neue Anfrage habe ich bereits gestellt. Ich melde mich umgehend sobald ich eine Aussage dazu habe. Deswegen vor dem Start, nochmal die Frage: wenn Heidelpay keine wiederkehrende jährliche Zahlung anbieten kann, wäre das ein Grund für dich einen anderen Bezahlungsanbieter zu nehmen?

**Comment by KlaudiaSt** [comment]
"Umstellung eines Zahlungsdienstanbieters" : Denke ist nicht schwierig, da die Daten exportiert werden könne, z.B. nach DATEV)
Habe bei Heidelpay wegen Jahres-Abo noch mal nachgefragt. Kann ich mir fast nicht vorstellen.

**Comment by timemb** [comment]
Ich habe update vom Entwickler des Plugins, also der Schnittstelle zur Kommunikation zwischen Heidelpay und der SocialEngine.

Es ist ein JA zu der Möglichkeit von wiederkehrenden jährlichen Bezahlungen. Sie haben sich vergangenen Monat mit Heidelpay dazu ausgetauscht.

Ich habe jetzt nochmal explizit nach dem Angebot zur Individualisierung gefragt.

Hier der Link zum Ticket und der Korrespondenz:
https://ticket.younetco.com/view.php?id=153777#reply


Ich glaube nicht, dass es hilft, wenn ich zum jetzigen Zeitpunkt bezüglich der Schnittstelle mit Herrn Damm spreche. Ich kann von der Programmierseite her wenig bis gar nichts hinzufügen. Die Schnittstelle muss das regeln und von der Programmierung davon habe ich keine Ahnung.

**Comment by KlaudiaSt** [comment]
Für den Zugang brauche ich E-Mailadresse und Ticket-ID.

Ich habe dir die Technische Dokumentation von Heidelpay geschickt. Leite die doch bitte an Younetco weiter. Ich würde ja mit denen reden, dafür reicht aber mein Englisch nicht.

**Comment by timemb** [comment]
E-Mailadresse ist meine. 

153777 ist die ID, dachte das funktioniert da die ID im Link enthalten ist.

**Comment by timemb** [comment]
Ich veranlasse den Kauf des Plugins und die Installation.

**Comment by KlaudiaSt** [comment]
Bitte gib mir Bescheid, wenn du weisst, wie lange die brauchen und was es kostet

**Comment by timemb** [comment]
Ich rechne damit, dass dieses Plugin morgen installiert ist.
Es kann dann in Anschluss an die Einstellung der Mitgliederlevel und Einstellung der Darstellung bei Registrierung #56 eingestellt werden.

**Comment by timemb** [comment]
Die Taiwanesen haben das neue Plugin noch nicht installieren können, da man den Bereich um „Packages & Plugins“ im Adminbereich nicht aufrufen kann. Ein erstes Problem konnte ich schnell beheben. Ein weiteres Problem führt dazu, dass man auf seine eigene Profil-Startseite geleitet wird. 
Eigentlich sollte diese Adresse zu den Packages & Plugins führen: https://www.herzensmenschen.com/admin/packages/
Kannst du ausprobieren, tut er leider nicht. Dieses Problem ist dem Support gemeldet, mit hoher Wichtigkeitsstufe.

**Comment by timemb** [comment]
Wir haben das Problem in den Weiterleitungen gefunden und behoben.
Die Taiwanesen können die Paymentgateway installieren.

**Comment by timemb** [comment]
Payment Gateway ist installiert.
Diese kann nun eingestellt werden.

Im Administrationsbereich unter dem Menüpunkt "Rechnung > Gateways" kannst du bei HeidelPay deine Daten eingeben.
oder diesen Link verwenden https://www.herzensmenschen.com/se/admin/payment/gateway wenn du angemeldet bist.

Wenn ich dich hier unterstützen soll, sag mit bescheid.

**Comment by KlaudiaSt** [comment]
Ja, so ganz verstehe ich das nicht.
Der Link führt zum Control Panel der SE,  Advanced Payment Gateway, wo bekomme ich die Daten für Sender, Login, Kennwort, Chanel her?
Ist doch was anderes als bei HeidelPay meine Daten zu hinterlegen, oder?

**Comment by timemb** [comment]
Das sollten Daten sein, die du von HeidelPay bekommst. Diese braucht die unsere Software SocialEngine um mit HeidelPay zu deinem Kundenkonto bei denen zu kommunizieren.

**Comment by KlaudiaSt** [comment]
Zur Anbindung des Bezahlsystems HeidelPay:

Ist eingerichtet und braucht nun, wie besprochen, die Daten von HeidelPay zur Kommunikation mit deinem Kundenkonto. Was hast du für Daten von Heidelpay erhalten? Brauchst du hier noch Unterstützung von mir bei der Einrichtung? Wie sehen die Daten zur Rechnung aus die HeidelPay nach Bezahlung eines Mitglieds zur Verfügung stellt? Du wolltest nach diesen Informationen Fragen, damit wir uns zur Mehrwertsteuer nochmal besprechen können, was die beste Lösung ist.
