### ISSUE TITLE
GoogleMaps aktivieren

### ISSUE THREAD

**Issue by KlaudiaSt** [timemb/herzenspeople#43]
GoogleMaps aktivieren

Tim:
Diese Suche wird über den Kartendienstanbieter geregelt und ist vermutlich leichter zu verstehen wenn wir die Kartenansicht von Google Maps wieder aktivieren (müssen wir aber nicht. 

Klaudia:
Doch, mach mal

**Comment by timemb** [comment]
Kartenansicht ist als Möglichkeit in der Suchausgabe aktiviert.
