### ISSUE TITLE
Mitgliedschaft beenden

### ISSUE THREAD

**Issue by KlaudiaSt** [timemb/herzenspeople#48]
Mitgliedschaft endet
 Klaudia:
Ich würde gerne die Option anbieten, wenn jemand ein Jahres-Abo abschließt, aber vorzeitig kündigen möchte, dass wir die bereits abgelaufenen Monate mit € 5 berechnen und den restlichen Betrag auszahlen. 
Tim:
Steht in den Nutzungsbedingungen, können wir gerne anpassen
Klaudia: 
Text kommt von mir

**Comment by KlaudiaSt** [comment]
Zu § 7 der Nutzungsbedingungen hinzufügen:

Hat ein Mitglied ein Jahres-Abo abgeschlossen, möchte aber, egal aus welchem Grund, vorzeitig kündigen, berechnen wir die die bereits abgelaufenden Monate mit dem jeweiligen Monatsbeitrag und zahlen den restlichen Beitrag aus.

**Comment by timemb** [comment]
Ist hinzugefügt. Des weiteren wurde in der Zwischenzeit ein neuer Artikel zum Newsletter hinzugefügt.
