### ISSUE TITLE
Mitgestalten-Seite

### ISSUE THREAD

**Issue by KlaudiaSt** [timemb/herzenspeople#49]
Warum, Input-Themen, Wie und wo wird Input umgesetzt

**Comment by KlaudiaSt** [comment]
Hier ist Dein Mitgestalten gefragt.

Je mehr Mitglieder ihr Wissen mit uns teilen, desto schneller bekommen wir eine umfangreiche, informative Datenbank mit innovativen, nachhaltigen, unkonventionellen und wertschätzenden Denk-, und Lösungsansätzen.

Nachdem wir Deinen Vorschlag geprüft haben, werden wir die Daten entsprechend bearbeiten.

Themen:
Interessante (Web-)Adressen
Verbesserungsvorschlag (inhaltlich)
Beschwerde (inhaltlich)
Lob

**Comment by timemb** [comment]
umgesetzt auf:
http://www.herzensmenschen.com/se/mitgestalten
