### ISSUE TITLE
AGB

### ISSUE THREAD

**Issue by timemb** [timemb/herzenspeople#5]
AGB sind drin, aber noch nicht vollständig, 

Adresse für Wiederruf ist zu überprüfen

**Comment by KlaudiaSt** [comment]
Nimm Martin raus und setz meinen Namen rein.

**Comment by timemb** [comment]
Sein Name nicht drin. Nur du. Die Formulierung war Aufgrund der Vorlage etwas komisch.

Du kannst die AGB / Nutzungsbedingungen hier einsehen: http://www.herzensmenschen.com/help/terms
oder in der Fußzeile auf Nutzungsbedingungen klicken.

**Comment by KlaudiaSt** [comment]
Ist das nun erledigt?

**Comment by timemb** [comment]
Wenn du die so abgenommen hast, ja.
