### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by KlaudiaSt** [timemb/herzenspeople#50]
Einleitungstext für Anfragen

**Comment by KlaudiaSt** [comment]
Hier kannst Du bei technischen Fragen den Support kontaktieren.
Sollte Dir ein Mitglied auffallen, dass sich Deiner Meinung nach,
 nicht nach unseren Werten verhält, bitte auch hier melden.

**Comment by timemb** [comment]
erledigt
http://www.herzensmenschen.com/se/support
