### ISSUE TITLE
Piktogram Herzensmenschen

### ISSUE THREAD

**Issue by KlaudiaSt** [timemb/herzenspeople#63]
Wir benötigen unser HM-Zeichen als Piktogram für die Web-Seiten unserer Mitglieder und Social Media.

**Comment by timemb** [comment]
Ich bin mir nicht sicher wie das Herz alleine wirkt aber wir können da mehrere Sachen ausprobieren.

vorab schonmal das Logo in weiß auf der CI-Farbe

![logo-mit-hintergrund](https://user-images.githubusercontent.com/13312142/31556462-75fddd48-b045-11e7-932c-506f1869b0dc.png)

**Comment by KlaudiaSt** [comment]
Es muss klein sein, so wie von allen anderen Sozialen Netzwerken.

Ich denke das Herz in weiss auf der CI-Farbe

**Comment by timemb** [comment]
Das kommt auf die Benutzung an. 

Als Icon in der Browserleiste zum Beispiel wird es als weißes Herz auf CI-Farbe gut funktionieren.

Für Werbezwecke sollten wir mehrere Versionen haben, und auch mehrere Größen und Formate des Logos. So, dass andere Leute es auch auf ihren Websites einbauen können. Ich glaube im Moment funktioniert das Herz ohne die Wortmarke werbemäßig noch nicht alleine. 

Welchen speziellen Fall anderer Sozialer Netzwerke meinst du noch?

**Comment by KlaudiaSt** [comment]
Soweit ich mich erinnern kann, gab es bei der Entwicklung des Logos schon mehrere Varianten.
Bitte lass mir diese per Mail zukommen.
Ansonsten sehe ich das genauso.
Nachfolgendes Beispiel von Sozialen Netzwerken
[Piktogram.docx](https://github.com/timemb/herzenspeople/files/1398100/Piktogram.docx)

**Comment by timemb** [comment]
test

**Comment by KlaudiaSt** [comment]
Habe noch keine Mail erhalten
