### ISSUE TITLE
GitHub Benachrichtigungen ect.

### ISSUE THREAD

**Issue by KlaudiaSt** [timemb/herzenspeople#65]
- Wo finde ich meine Benachrichtigungen als Übersicht? 
- Und wie kann ich dir eine Nachricht schreiben? 
- Wo kann ich sehen, wenn eine Frage/Antwort in einem Label geschrieben worden ist bzw. ein Label bearbeitet worden ist?
- Kann ich Screen-Shots direkt einfügen, oder müssen die erst auf dem Rechner gespeichert werden?
- Gibt es sowas wie GitHub auch in Deutsch? 

Im Moment zeigen die Labels nur an, vor wieviel Tagen sie angelegt wurden, wo ersehe ich das Erstellungs-Datum?

Bitte lege noch an als jeweils ein Label:
- Aufgabe Klaudia
- Aufgabe Tim
- Aufgabe Thomas
oder wir lassen das Label Aufgabe ganz weg, denn wenn unser Name da steht, ist ja eigentlich klar, dass wir das bearbeiten müssen, oder?

**Comment by timemb** [comment]
- Benachrichtigungen findest du ganz oben in der dunkelgrauen Leiste (Glocken-Symbol)

- in diesem System gibt es glaube ich keine Möglichkeit Direktnachrichten zu schreiben

- Du verwechselst hier Label und Issue. Issues sind die Aufgaben, Labels sind die Post-Its die wir zur Sortierung dort anbringen um diese zu kategorisieren. Wenn du Oben auf den Reiter "Issues" klickst kommst du zur Überischt aller Issues im Projekt. Diese haben dann Links am Issue eine dünne blaue Markierung, wenn du den neuesten Kommentar (Antwort) noch nicht gesehen hast.

- Soweit ich das sehe, können Bilder nur eingefügt werden wenn sie von der Festplatte kommen, du sie also vorher gespeichert hast. Eine gute Lösung hierfür ist das open source Programm "Greenshot".

- Github selber gibt es ja leider nicht auf deutsch. Eine Alternative auf Deutsch für die Funktionen die wir nutzen kenne ich als Kostenpflichtige Projektmanagement Software. Eine Alternative dazu müsste ich recherchieren.

- Wenn du mit dem Mauszeiger auf dieser Zeitangabe bleibt, wird dir kurz darauf das Datum und die Uhrzeit zu dieser Zeitangabe angezeigt.

Diese Labels sind meiner Meinung nach überflüssig, da es die Personen, sowie Frage und Aufgabe als einzelne Labels gibt. Diese können per Mausklick geändert werden. So kann ich dir zum Beispiel anzeigen, dass ich diesen Issue kommentiert habe und nun zur Info für dich einfach nur mit Klaudia markiere.
