### ISSUE TITLE
Profil-Kriterien

### ISSUE THREAD

**Issue by KlaudiaSt** [timemb/herzenspeople#67]
Gezielte Kontaktaufnahme dank Profil-Voting (erweiterte Suche)

Was meinst du mit Profil-Voting?

**Comment by KlaudiaSt** [comment]
Ich meine dass gezielte Suchen nach Kriterien, ist Profil-Matching verständlicher? Oder einfach nur "Profil-Kriterien"?

**Comment by timemb** [comment]
Ich glaube "Suche nach Profik-Kriterien" ist verständlicher.
Bei Matching habe ich direkt die Assoziation, dass das System etwas automatisch macht.

Für den Punkt "Erweiterte Suche" merke ich jetzt also **"Suche nach Profik-Kriterien"**

**Comment by KlaudiaSt** [comment]
Okay
