### ISSUE TITLE
Geburtsjahr

### ISSUE THREAD

**Issue by KlaudiaSt** [timemb/herzenspeople#70]
Das jüngste Jahr hört bei 2001 auf.
Da wir aber auch Minderjährige zulassen, muss das geändert werden.

**Comment by timemb** [comment]
Ich kann bei dieser Profilfrage das Mindestalter angeben.
Dieses ist derzeit auf "16" Jahre eingestellt. 

Was wäre hier dein Wunsch als Mindestalter?

**Comment by KlaudiaSt** [comment]
Keins

**Comment by timemb** [comment]
eingestellt
