### ISSUE TITLE
Mailadressen

### ISSUE THREAD

**Issue by KlaudiaSt** [timemb/herzenspeople#72]
Wir haben das Problem, dass nicht nachvollzogen werden kann, welche Datenbank mit dem Crawl-Programm durchsucht worden ist, laut Thomas.

Was passiert, wenn wir doppelte Adressen in der Liste haben?
Kann CleverReach die aussortieren?

**Comment by timemb** [comment]
CleverReach sortiert doppelte Adressen sofort und automatisiert aus.

Wenn man jetzt z.B. 100 Adressen hinzufügt, die alle schon in der Empfängergruppe enthalten sind, meldet CleverReach zurück, dass der Vorgang erfolgreich abgeschlossen wurde und 0 Adressen hinzugefügt wurden und 100 Duplikate in der neuen Liste waren.
