### ISSUE TITLE
Weiterleitungsproblem beheben

### ISSUE THREAD

**Issue by timemb** [timemb/herzenspeople#73]
Es besteht derzeit ein Problem, dass einen Klick auf den Navigationspunkt "Seiten" zu einem Fehler führt.
Mann kommt erst auf den Bereich Seiten, wenn man anschließend noch einmal auf den Navigationspunkt "Seiten" klickt. 

Dies ist ein ungewohntes Verhalten für eine Website und es wirkt als wäre dieser Bereich kaputt. Wenn es beim ersten mal kaputt wirkt, kommt man als Benutzer nicht direkt auf die Idee nochmal auf diesen Menüpunkt zu klicken.

Da es sich hier um eine der Hauptfunktionen und Anreize für Unternehmen ist, muss dieses Problem behoben werden.

Im Administrationsbereich führt dieser Sachverhalt auch zu einem Weiterleitungsfehler. Nicht so großes Problem, da wir Admins davon wissen.

Das Problem ist identifiziert. Eine Lösung wird mit Ranketing beschlossen und kurzfristig umgesetzt. Meinung von unserem Support bei SocialEngineAddons (Inder) hierzu wurde bereits eingeholt.

Derzeitige Lösungsansätze:
1.	Die Domain direkt auf den Unterordner „/se“ leiten (nicht via HTACCESS).
2.	Den Inhalt des Ordners „/se“ verschieben damit die SocialEngine im Server HTML-Root liegt.

**Comment by KlaudiaSt** [comment]
Wie geht es hier weiter???

**Comment by timemb** [comment]
Ist bei Ranketing angefragt. Hatte heute dazu nochmals nachgehakt.

**Comment by timemb** [comment]
Weiterleitungsproblem des Navigationspunktes "Seiten" konnte anderweitig behoben werden.
Weitere Arbeiten von Serverseite sind, aus meiner Sicht, derzeit nicht notwendig
