### ISSUE TITLE
Daten, Verträge, Zugänge  Inder, GitHub und Clever Reach

### ISSUE THREAD

**Issue by KlaudiaSt** [timemb/herzenspeople#76]
Bitte schicke mir o.g. Daten zu

**Comment by KlaudiaSt** [comment]
Wann bekomme ich die Daten?

**Comment by timemb** [comment]
Ich schicke sie dir nochmal zu.

Hast du sie letztes Mal denn erhalten oder nicht? ich schicke ungern solche Daten hin und her.

**Comment by KlaudiaSt** [comment]
Die Mail habe ich bekommen. Clever Reach ist enthalten.

Ich brauche noch den Support-Vertrag der Inder und deine Kontaktdaten, sowie sämtlichen Schriftverkehr mit den Inder.

Bitte ändere herzenspeople auf meinen Namen
