### ISSUE TITLE
Veranstaltungserstellung - Online Event

### ISSUE THREAD

**Issue by timemb** [timemb/herzenspeople#9]
Klaudia:
Kannst du den Link so schreiben:  „Online Event, klick hier“?

**Comment by timemb** [comment]
Ja, habe ich. Sieht aber komisch aus, aufgrund des Fragezeichens.

**Comment by timemb** [comment]
Klaudia:
Das Fragezeichen gehört auch zu der Frage und nicht zum Link  Bitte rausnehmen

**Comment by timemb** [comment]
Das ist ja das blöde an dieser Stelle, das Fragezeichen ist an dieser Stelle nicht bearbeitbar. Ich habe die Möglichkeit mittels der Übersetzungsdatei, den Teil vor dem Link und den Link selbst zu bearbeiten. Aber nicht das Fragezeichen. Müsste ich in die Programmierung des Plugins um das zu ändern. Mein Vorschlag: das „klicke hier“ vorerst wieder zu entfernen.

**Comment by timemb** [comment]
Klaudia:
Okay,  kannst dann den Link so schreiben   ONLINE EVENT oder (Klick hier)Online-Event

**Comment by timemb** [comment]
ja

![online veranstaltungen](https://user-images.githubusercontent.com/13312142/30394097-1bd5f930-9890-11e7-8953-5a4e588b533b.png)

**Comment by KlaudiaSt** [comment]
Okay. Erledigt

**Comment by KlaudiaSt** [comment]
Erledigt. 
Bitte schliessen, kann ich nicht
